#!/usr/bin/env bash

declare -A OPTIONS=(
	["Lock"]="xsecurelock"
	["Logout"]="i3-msg exit"
	["Poweroff"]="systemctl poweroff"
	["Reboot"]="systemctl reboot"
	["Suspend"]="systemctl suspend"
)

selected=$(IFS=$'\n' eval 'echo "${!OPTIONS[*]}"' | sort | rofi -dmenu -i -p "power")
eval "${OPTIONS[${selected}]}"
