#!/usr/bin/env bash

set -euxo pipefail

if ! command -v brew &>/dev/null; then
    eval "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

brew bundle --cleanup --no-upgrade --file=- <<EOF
tap "buo/cask-upgrade"
tap "felixkratz/formulae"
tap "hashicorp/tap"
tap "homebrew/services"
tap "nikitabobko/tap"
tap "oven-sh/bun"

brew "aria2"
brew "atool"
brew "atuin"
brew "bandwhich"
brew "bash"
brew "bat"
brew "buf"
brew "chezmoi"
brew "direnv"
brew "eza"
brew "fd"
brew "felixkratz/formulae/borders"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "gemini-cli"
brew "gh"
brew "git"
brew "git-delta"
brew "git-recent"
brew "go"
brew "go-task"
brew "golangci-lint"
brew "hashicorp/tap/terraform"
brew "httpie"
brew "hyperfine"
brew "jq"
brew "litecli"
brew "llm"
brew "mas"
brew "mimalloc"
brew "mycli"
brew "neovim"
brew "nushell"
brew "oven-sh/bun/bun"
brew "pandoc"
brew "pgcli"
brew "pipx"
brew "pkg-config"
brew "poppler"
brew "protobuf"
brew "python"
brew "rbw"
brew "ripgrep-all"
brew "rsync"
brew "shellcheck"
brew "sqlc"
brew "starship"
brew "rustup"
brew "tokei"
brew "vivid"
brew "watch"
brew "watchexec"
brew "yq"
brew "zig"
brew "zoxide"
brew "zsh"

cask "android-ndk"
cask "beekeeper-studio"
cask "bitwarden"
cask "bluesnooze"
cask "brave-browser"
cask "command-x"
cask "cursor"
cask "domzilla-caffeine"
cask "font-ubuntu-mono-nerd-font"
cask "google-cloud-sdk"
cask "iina"
cask "jordanbaird-ice"
cask "karabiner-elements"
cask "lens"
cask "localsend"
cask "monitorcontrol"
cask "music-decoy"
cask "ngrok"
cask "nikitabobko/tap/aerospace"
cask "notion"
cask "obsidian"
cask "orbstack"
cask "postman"
cask "powershell"
cask "raycast"
cask "reader"
cask "spotify"
cask "stats"
cask "stretchly", args: { no_quarantine: true }
cask "tg-pro"
cask "visual-studio-code"
cask "warp"
cask "wezterm"
cask "whatsapp"
cask "zoom"

# Work only
brew "java"
brew "localstack"
brew "minikube"
brew "minio/minio/mc"
brew "node"
brew "pixi"
brew "pnpm"
brew "postgresql@14"
brew "python@3.11"
brew "redis"
brew "tesseract"
brew "vespa-cli"
cask "linear-linear"
cask "loom"
cask "microsoft-teams"

# Experimental
brew "yazi"
cask "shottr"
EOF

cargo install cargo-msrv cargo-ndk cargo-outdated cargo-udeps cargo-zigbuild flamegraph
gcloud components install gke-gcloud-auth-plugin
gh extension install github/gh-copilot
go install github.com/google/pprof@latest
pipx install argcomplete poetry

rustup-init -y --no-modify-path --no-update-default-toolchain
rustup toolchain list | grep -q nightly || rustup toolchain install nightly
